workflows:
  ios-pwa-build:
    name: Build MedSci iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ChaveMedSci # Esse é o nome que você deu para a chave no Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.suaempresa.medsci # ⚠️ ATENÇÃO: Troque pelo seu Bundle ID real!
      vars:
        XCODE_WORKSPACE: "MedSci.xcworkspace"
        XCODE_SCHEME: "MedSci"
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Build and sign iOS App
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - seu-email@gmail.com # Coloque seu e-mail aqui para ser avisado quando o app ficar pronto
