workflows:
  ios-pwa-build:
    name: Build MedSci iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ChaveMedSci
    environment:
      groups:
        - apple_certs
      vars:
        XCODE_WORKSPACE: "MedSci.xcworkspace"
        XCODE_SCHEME: "MedSci"
    scripts:
      - name: Initialize Mac Keychain
        script: |
          keychain initialize
      - name: Definitive Fix - Zero Entitlements
        script: |
          # 1. Esvazia fisicamente qualquer arquivo de permissão (deixa em branco)
          find . -name "*.entitlements" -type f -exec sh -c 'echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"><plist version=\"1.0\"><dict/></plist>" > "{}"' \;
          
          # 2. Apaga as chaves de Entitlements do arquivo de configuração do Xcode
          sed -i '' 's/CODE_SIGN_ENTITLEMENTS = .*;/CODE_SIGN_ENTITLEMENTS = "";/g' MedSci.xcodeproj/project.pbxproj || true
      - name: Fetch and Create Apple Signing Profiles
        script: |
          app-store-connect fetch-signing-files "com.medsci.app.medsciprotocolos" \
            --type IOS_APP_STORE \
            --create
      - name: Add Certificates to Mac Keychain
        script: |
          keychain add-certificates
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Apply Provisioning Profiles to Xcode
        script: |
          xcode-project use-profiles
      - name: Build and sign iOS App (Overriding Capabilities)
        script: |
          # A ORDEM DIRETA: O comando CODE_SIGN_ENTITLEMENTS="" no final força o Xcode a compilar sem restrições
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            CODE_SIGN_ENTITLEMENTS=""
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
