workflows:
  ios-pwa-build:
    name: Build MedSci iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ChaveMedSci
    environment:
      groups:
        - apple_certs
      vars:
        XCODE_WORKSPACE: "MedSci.xcworkspace"
        XCODE_SCHEME: "MedSci"
    scripts:
      - name: Initialize Mac Keychain
        script: |
          keychain initialize
      - name: The Eradicator (Python Deep Clean)
        script: |
          python3 -c '
          import os, re
          # 1. Varre o projeto e esvazia todos os arquivos de permissao
          for root, dirs, files in os.walk("."):
              for file in files:
                  if file.endswith(".entitlements"):
                      with open(os.path.join(root, file), "w") as f:
                          f.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"><plist version=\"1.0\"><dict/></plist>")
          
          # 2. Abre o coracao do Xcode e arranca as exigencias
          pbx = "MedSci.xcodeproj/project.pbxproj"
          if os.path.exists(pbx):
              with open(pbx, "r") as f:
                  content = f.read()
              # Deleta o bloco inteiro de capacidades do sistema
              content = re.sub(r"SystemCapabilities\s*=\s*\{.*?\};", "", content, flags=re.DOTALL)
              with open(pbx, "w") as f:
                  f.write(content)
          '
      - name: Fetch and Create Apple Signing Profiles
        script: |
          app-store-connect fetch-signing-files "com.medsci.app.medsciprotocolos" \
            --type IOS_APP_STORE \
            --create
      - name: Add Certificates to Mac Keychain
        script: |
          keychain add-certificates
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Apply Provisioning Profiles to Xcode
        script: |
          xcode-project use-profiles
      - name: Build and sign iOS App
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
