workflows:
  ios-pwa-build:
    name: Build MedSci iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ChaveMedSci
    environment:
      groups:
        - apple_certs
      vars:
        XCODE_WORKSPACE: "MedSci.xcworkspace"
        XCODE_SCHEME: "MedSci"
        BUNDLE_ID: "com.medsci.app.medsciprotocolos"
    scripts:
      - name: Initialize Mac Keychain
        script: |
          keychain initialize
      - name: PWABuilder Ultimate Scrub & Cache Clean
        script: |
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" MedSci.xcodeproj/project.pbxproj || true
          find . -name "*.entitlements" -type f -delete
          sed -i '' '/CODE_SIGN_ENTITLEMENTS/d' MedSci.xcodeproj/project.pbxproj || true
          sed -i '' '/SystemCapabilities/,/};/d' MedSci.xcodeproj/project.pbxproj || true
          sed -i '' '/com.apple.Push/d' MedSci.xcodeproj/project.pbxproj || true
          sed -i '' '/com.apple.Developer.associated-domains/d' MedSci.xcodeproj/project.pbxproj || true
          find . -name "Info.plist" -not -path "*/Pods/*" -exec /usr/libexec/PlistBuddy -c "Delete :UIBackgroundModes" {} \; || true
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
      - name: Fetch and Create Apple Signing Profiles
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Add Certificates to Mac Keychain
        script: |
          keychain add-certificates
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Apply Provisioning Profiles to Xcode
        script: |
          xcode-project use-profiles
      - name: Build and sign iOS App
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
