workflows:
  ios-pwa-build:
    name: Build MedSci iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ChaveMedSci
    environment:
      groups:
        - apple_certs
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.medsci.app.medsciprotocolos
      vars:
        XCODE_WORKSPACE: "MedSci.xcworkspace"
        XCODE_SCHEME: "MedSci"
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Force Bundle ID
        script: |
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = com.medsci.app.medsciprotocolos;/g" MedSci.xcodeproj/project.pbxproj || true
      - name: Apply Provisioning Profiles to Xcode
        script: |
          xcode-project use-profiles
      - name: Build and sign iOS App
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
