workflows:
  ios-pwa-build:
    name: Build MedSci iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ChaveMedSci
    environment:
      groups:
        - apple_certs
      vars:
        XCODE_WORKSPACE: "MedSci.xcworkspace"
        XCODE_SCHEME: "MedSci"
    scripts:
      - name: Initialize Mac Keychain
        script: |
          keychain initialize
      - name: Bypass Apple Requirements (Hack)
        script: |
          ENTITLEMENTS_FILE=$(find . -type f -name "*.entitlements" | head -n 1)
          if [ -n "$ENTITLEMENTS_FILE" ]; then
            /usr/libexec/PlistBuddy -c "Delete :aps-environment" "$ENTITLEMENTS_FILE" || true
            /usr/libexec/PlistBuddy -c "Delete :com.apple.developer.associated-domains" "$ENTITLEMENTS_FILE" || true
          fi
          sed -i '' '/com.apple.Push/d' MedSci.xcodeproj/project.pbxproj || true
          sed -i '' '/com.apple.Developer.associated-domains/d' MedSci.xcodeproj/project.pbxproj || true
      - name: Fetch and Create Apple Signing Profiles
        script: |
          app-store-connect fetch-signing-files "com.medsci.app.medsciprotocolos" \
            --type IOS_APP_STORE \
            --create
      - name: Add Certificates to Mac Keychain
        script: |
          keychain add-certificates
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Apply Provisioning Profiles to Xcode
        script: |
          xcode-project use-profiles
      - name: Build and sign iOS App
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
