workflows:
  ios-pwa-build:
    name: Build MedSci iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ChaveMedSci
    environment:
      groups:
        - apple_certs
      vars:
        XCODE_WORKSPACE: "MedSci.xcworkspace"
        XCODE_SCHEME: "MedSci"
    scripts:
      - name: Initialize Mac Keychain
        script: |
          keychain initialize
      - name: Nuclear Option - Remove All Entitlements (Ruby)
        script: |
          gem install xcodeproj --no-document
          ruby -e "
          require 'xcodeproj'
          project = Xcodeproj::Project.open('MedSci.xcodeproj')
          
          # 1. Remove as capacidades do sistema do alvo principal
          if project.root_object.attributes['TargetAttributes']
            project.root_object.attributes['TargetAttributes'].each do |target, attributes|
              attributes.delete('SystemCapabilities')
            end
          end
          
          # 2. Remove as exigencias de arquivos Entitlements de todas as configuracoes
          project.build_configurations.each do |config|
            config.build_settings.delete('CODE_SIGN_ENTITLEMENTS')
          end
          project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings.delete('CODE_SIGN_ENTITLEMENTS')
            end
          end
          
          # 3. Salva o projeto completamente limpo
          project.save
          "
          # 4. Deleta fisicamente os arquivos .entitlements do disco para nao sobrar rastro
          find . -name '*.entitlements' -type f -delete
      - name: Fetch and Create Apple Signing Profiles
        script: |
          app-store-connect fetch-signing-files "com.medsci.app.medsciprotocolos" \
            --type IOS_APP_STORE \
            --create
      - name:
